language: ruby
cache: bundler
gemfile: /Gemfile
script:
  - bundle exec jekyll algolia --source / --destination /_site --config /_config.yml
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master
rvm:
 - 2.4
