language: ruby
cache: bundler
gemfile: docs/Gemfile
script:
  - bundle exec jekyll algolia --source docs --destination docs/_site --config docs/_config.yml
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master
rvm:
 - 2.4