# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MvvmCross
description: > # this means to ignore newlines until "baseurl:"
  MvvmCross is a convention based MVVM framework for Xamarin and Windows,
  with strong community support, filled to the brim with useful features.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.mvvmcross.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: compressed

# theme: minima
# End

# Gem settings
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jekyll-github-metadata

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - SITECHANGELOG.md
# End

# Github metadata settings
repository: MvvmCross/MvvmCross
# End

# jekyll-seo-tag settings
social:
  name: MvvmCross
  links:
    - https://twitter.com/MvvmCross
    - https://github.com/MvvmCross

logo: /assets/img/logo/MvvmCross-avatar.png

twitter:
  username: MvvmCross
#End

# Date format settings
date_format: "%b %-d, %Y"
# End

# Site permalink settings
permalink: /:title/
# End

# Collections settings
collections:
  documentation:
    output: true
    permalink: /:collection/:path
# End

# Site menu settings
menu:
  - title: "Blog"
    url: "/blog"
  - title: "Documentation"
    url: "/documentation"
  - title: "Support"
    url: "/support"
# End

category_order:
  - 'Getting-started'
  - 'Fundamentals'
  - 'Advanced'
  - 'Platforms'
  - 'Plugins'
  - 'Samples'
  - 'Tutorials'
  - 'Upgrading'
  - 'Contributing'