# Theme Settings
theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "custom"

# Site Settings
locale: "en-US"
title: "Site Title"
description: "An amazing website."
url: ""
baseurl: ""
repository: ""

# Site Author
author:
  name: "Michael Miller"
  # avatar: "/assets/images/bio-photo.jpg"
  # bio: 
  # location: 
  # email: 

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url:
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:
  since: "2013"

# Reading Files
include:
  - .htaccess
  - _pages

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Markdown Processing
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Pagination with jekyll-paginate
paginate: 5
paginate_path: /page:num/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: 
      share: true
      related: true

# Optional Integrations (commented out for future use)

# comments:
#   provider: 
#   disqus:
#     shortname: 
#   discourse:
#     server: 
#   facebook:
#     appid: 
#     num_posts: 
#     colorscheme: 
#   utterances:
#     theme: 
#     issue_term: 
#   giscus:
#     repo_id: 
#     category_name: 
#     category_id: 
#     discussion_term: 
#     reactions_enabled: 
#     theme: 
#     strict: 
#     input_position: 
#     emit_metadata: 
#     lang: 
#     lazy: 
#   staticman:
#     branch: 
#     endpoint: 
# reCaptcha:
#   siteKey: 
#   secret: 
# atom_feed:
#   path: 
#   hide: 
# search: 
# search_full_content: 
# search_provider: 
# lunr:
#   search_within_pages: 
# algolia:
#   application_id: 
#   index_name: 
#   search_only_api_key: 
#   powered_by: 
# google:
#   search_engine_id: 
#   instant_search: 
# google_site_verification: 
# bing_site_verification: 
# naver_site_verification: 
# yandex_site_verification: 
# baidu_site_verification: 
# twitter:
#   username: 
# facebook:
#   username: 
#   app_id: 
#   publisher: 
# og_image: 
# social:
#   type: 
#   name: 
#   links: 

# analytics:
#   provider: 
#   google:
#     tracking_id: 
#     anonymize_ip: 