# Jekyll ì„¤ì •
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Minimal Mistakes í…Œë§ˆ ì„¤ì •
minimal_mistakes_skin: "default" # ì›í•˜ëŠ” ìŠ¤í‚¨ìœ¼ë¡œ ë³€ê²½ ê°€ëŠ¥
# theme: "minimal-mistakes-jekyll"
# remote_theme: "mmistakes/minimal-mistakes"

# ğŸ›‘ ì‚¬ì´íŠ¸ í•„ìˆ˜ ì„¤ì • (ë°˜ë“œì‹œ ìˆ˜ì •í•˜ì„¸ìš”!) ğŸ›‘
title: "Orange Tech blogs"
title_separator: "-"
# subtitle: "ì‚¬ì´íŠ¸ë¥¼ ì„¤ëª…í•˜ëŠ” ì§§ì€ íƒœê·¸ë¼ì¸"
url: "https://o5l3.github.io" # ì‚¬ìš©ì ê³„ì • ë„ë©”ì¸ìœ¼ë¡œ ì„¤ì • (o5l3.github.io)
baseurl: "/OrangeLabs_blog" # ì €ì¥ì†Œ ì´ë¦„ê³¼ ë™ì¼í•˜ê²Œ ì„¤ì • (o5l3.github.io/OrangeLabs_blog)
repository: "o5l3/OrangeLabs_blog" # GitHub ì‚¬ìš©ìëª…/ì €ì¥ì†Œ ì´ë¦„

# SEO Related
# google_site_verification:
naver_site_verification: # ë„¤ì´ë²„ ê²€ìƒ‰ ë“±ë¡ ì‹œ í•„ìš”

# Analytics
analytics:
  provider: # "google-gtag", "google-universal" ë“± ì„ íƒ
  google:
    tracking_id: # êµ¬ê¸€ ì• ë„ë¦¬í‹±ìŠ¤ ID

# Site Footer
footer:
  links:
    - label: "Notion"
      icon: "fab fa-fw fa-twitter-notion"
      url: "https://o5l3.notion.site/"
  since: "2023"

# Outputting
permalink: /:categories/:title/
timezone: "Asia/Seoul" # ì‹œê°„ëŒ€ ì„¤ì • (ì„ íƒ ì‚¬í•­)

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Defaults (í¬ìŠ¤íŠ¸ì— ê¸°ë³¸ìœ¼ë¡œ ì ìš©ë˜ëŠ” ë ˆì´ì•„ì›ƒ)
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true # ëŒ“ê¸€ ê¸°ëŠ¥ í™œì„±í™” ì—¬ë¶€
      share: true
      related: true

# Reading Files
include:
  - .htaccess
  - _pages
# í•„ìš”í•œ íŒŒì¼ë§Œ ë‚¨ê¸°ê³  ë‚˜ë¨¸ì§€ Exclude í•­ëª©ì€ ëª¨ë‘ ì œê±°ë¨
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - Rakefile
  - README.md
