# Site wide configuration

title:            Site Title
locale:           en_US
url:              http://localhost:4000


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Your Name
  avatar: bio-photo.jpg
  bio: "Describe your self."
  email: 
  disqus-shortname: 
  twitter: 
  facebook: 
  google:
    plus: 
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: 
  stackoverflow:
  linkedin:
  instagram: 
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
