# Site wide configuration

title:            Pedro Piñera
locale:           en_US
# url:              http://127.0.0.1:4000
url:              http://www.ppinera.es
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - emoji_for_jekyll

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

# Site owner
owner:
  name: Pedro Piñera
  avatar: others/bio-photo.jpg
  bio: "Mobile Engineer currently working on 8fit and Open-Source ♥"
  email: "pepibumur@gmail.com"
  disqus-shortname: 
  twitter: "pepibumur"
  facebook: "pepibumur"
  disqus-shortname: "pedropiera"
  google:
    plus: "PedroPiñeraBuendia"
    analytics: UA-3325566-3
    verify: aEqj73Nc7NEwi7EjfpLlUhdeh9X3_IGO-7NyqBDSspk
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: "pepibumur"
  exposure: "pepibumur"
  stackoverflow: "963511/pedro-piñera-buendia"
  linkedin: #linkedin
  instagram: pepibumur
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: "pepibumur"

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
