# Site wide configuration

title:            Mind Stuff
locale:           en_US
url:              http://localhost:4000
#url:              http://eddiekollar.github.io
#url:              http://eddiekollar.com


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Eddie Kollar
  avatar: monkey-thinking.png
  bio: "Describe your self."
  email: eddie.kollar@gmail.com
  disqus-shortname: 
  twitter: eddiekollar
  facebook: #username
  google:
    plus: eddiekollar
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: eddiekollar
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: eddiekollar
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
