project:
  type: website
  preview: 
    port: 4909
  resources:
    - "assets/images/sipbs_compbiol.png"
    - "assets/images/avatars/leighton_profile.jpg"

website:
  title: "SIPBS CompBiol"
  site-url: https://sipbs-compbiol.github.io/
  description: "SIPBS Computational Biology Group"
  favicon: "icon_32.png"
  cookie-consent:
    type: express
  open-graph:
    locale: en_GB
    description: "The SIPBS CompBiol group pages"
  navbar:
    logo: ./assets/images/sipbs_compbio.png
    right:
      - text: "Home"
        file: index.qmd
      - text: "Group"
        menu:
        - text: "Who We Are"
          href: who_we_are.qmd
#        - text: "What We Do"
#          href: what_we_do.qmd
        - text: "Code of Conduct"
          href: code_of_conduct.qmd
        - text: "Responsibilities"
          href: responsibilities.qmd
        - text: "Philosophy"
          href: philosophy.qmd
      - text: "Activities"
        menu: 
        - text: "Blog"
          href: blog.qmd
        - text: "Publications"
          href: references.qmd
#        - text: "Hacky Hour"
#          href: hacky_hour.qmd
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app/profile/sipbscompbiol.bsky.social
      - icon: github
        href: https://github.com/sipbs-compbiol/sipbs-compbiol.github.io
#      - icon: twitter
#        href: https://twitter.com/scompbiol
      - icon: rss
        href: index.xml
  page-footer: 
    left: This site ¬© University of Strathclyde 2024
  announcement: 
    icon: info-circle
    dismissable: true
    content: "Funded PhD opportunity to study mixed bacterial infection in potato: [APPLY HERE](https://www.gla.ac.uk/postgraduate/doctoraltraining/northwestbio/projects/pathogens/futurethreatstocropprotectiontheroleofmixedpectobacteriuminfectionsindiseaserisk/) - Closing date Monday 6th January 2025"
    type: info
    position: below-navbar
    background: "blueviolet"

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    css: styles.css
    embed-resources: true

editor: source

custom-callout:
  callout-publications:
    title: "Publications"
    icon-symbol: "üìö"
    color: "orange"
  callout-scientist-blue:
    icon-symbol: "üßë‚Äçüî¨"
    color: "cadetblue"
  callout-scientist-purple:
    icon-symbol: "üßë‚Äçüî¨"
    color: "darkorchid"
  callout-scientist-peach:
    icon-symbol: "üßë‚Äçüî¨"
    color: "peachpuff"


filters:
- custom-callout

execute:
  freeze: auto