version: "3"

services:
  jekyll_custom:
    build: .
    command: bash -c "
      rm -f Gemfile.lock
      && bundler exec jekyll serve --watch --port=8080 --host=0.0.0.0 --livereload --verbose --trace"
    ports:
      - 8080:8080
    volumes:
      - .:/srv/jekyll