name: Updater (WIP)

on:
  schedule:
    - cron: 0 0 * * 0

jobs:
  update:
    if: github.repository_owner == 'wowchemy'
    runs-on: ubuntu-latest
    steps:
      - uses: wowchemy/gh-action-updater@v1
        with:
          feed-url: https://wowchemy.com/blog/index.xml
          readme-section: news
          branch: main
